name: dpcca
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py37_0
  - cffi=1.12.1=py37hb5b8e2f_0
  - cycler=0.10.0=py37_0
  - freetype=2.9.1=hb4e5f40_0
  - intel-openmp=2019.1=144
  - jpeg=9b=he5867d9_2
  - kiwisolver=1.0.1=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.36=ha441bb4_0
  - libtiff=4.0.10=hcb84e12_2
  - matplotlib=3.0.2=py37h54f8f79_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py37h5e564d8_0
  - mkl_random=1.0.2=py37h27c97d8_0
  - ncurses=6.1=h0a44026_1
  - ninja=1.8.2=py37h04f5b5a_1
  - numpy=1.16.2=py37hacdab7b_0
  - numpy-base=1.16.2=py37h6575580_0
  - olefile=0.46=py37_0
  - openssl=1.1.1b=h1de35cc_1
  - pillow=5.4.1=py37hb68e598_0
  - pip=19.0.3=py37_0
  - pycparser=2.19=py37_0
  - pyparsing=2.3.1=py37_0
  - python=3.7.2=haf84260_0
  - python-dateutil=2.8.0=py37_0
  - pytz=2018.9=py37_0
  - readline=7.0=h1de35cc_5
  - scikit-learn=0.20.2=py37h27c97d8_0
  - scipy=1.2.1=py37h1410ff5_0
  - setuptools=40.8.0=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.26.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - tornado=5.1.1=py37h1de35cc_0
  - wheel=0.33.1=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pytorch=1.0.1=py3.7_2
  - torchvision=0.2.2=py_3
  - pip:
    - coverage==4.5.2
    - nose2==0.8.0
    - torch==1.0.1.post2
prefix: /Users/gwg/miniconda3/envs/dpcca

