name: dpcca
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.1.23
  - certifi=2018.11.29
  - cffi=1.12.1
  - cycler=0.10.0
  - freetype=2.9.1
  - intel-openmp=2019.1
  - jpeg=9b
  - kiwisolver=1.0.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.36
  - libtiff=4.0.10
  - matplotlib=3.0.2
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - ncurses=6.1
  - ninja=1.8.2
  - numpy=1.16.2
  - numpy-base=1.16.2
  - olefile=0.46
  - openssl=1.1.1b
  - pillow=5.4.1
  - pip=19.0.3
  - pycparser=2.19
  - pyparsing=2.3.1
  - python=3.7.2
  - python-dateutil=2.8.0
  - pytorch=1.0.1
  - pytz=2018.9
  - readline=7.0
  - scikit-learn=0.20.2
  - scipy=1.2.1
  - setuptools=40.8.0
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.8
  - torchvision=0.2.2
  - tornado=5.1.1
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - coverage==4.5.2
    - nose2==0.8.0
prefix: /Users/gwg/miniconda3/envs/dpcca

